### PR TITLE
Add a new job for publishing docker image to GitHub Container Registry

### PR DESCRIPTION
**Pull request by sters**
## WHAT

This PR adds a new CI job for publishing docker image to GitHub Container Registry in the release workflow.

You can confirm the result on my forked repo:
- [Job log](https://github.com/sters/wrench/actions/runs/9958752332/job/27513880966)
- [Packages](https://github.com/sters/wrench/pkgs/container/wrench)

## WHY

To provide a continuous build for the docker image related to releases.
And related to this comment: https://github.com/cloudspannerecosystem/wrench/pull/97#issuecomment-1826669157

### CODE REVIEW

**Comment by sters** [comment]
I don't know who can review on this repo... Maybe it's better to add CODEOWNER file.

Anyway, I think @shuheiktgw can do.
Could you check this PR when you have time?

**Review by zoncoen — APPROVED** [review]
Thank you for this work! LGTM

**Review by shuheiktgw — APPROVED** [review]
LGTM!

**Comment by shuheiktgw** [comment]
It seems to work great 🎉 
https://github.com/cloudspannerecosystem/wrench/pkgs/container/wrench

**Comment by sters** [comment]
Thanks all!

**Comment by Shion1305** [comment]
Thanks for implementing the workflow! I'll close #97

**Comment by comebackoneyear** [comment]
Would it be possible to add support for arm images? I'm using the github action runners `linux/arm64/v8` but also m2 mac.

**Pull request merged**
