### PR TITLE
👷 Implement CI that builds image and pushes to DockerHub

### PR DESCRIPTION
**Pull request by Shion1305**
I'm working at Merpay cashio team as an intern!
Feel free to contact me regarding this PR :)
(Slack name: `@Shion(Intern)` )

## WHAT
Implemented GitHub Actions that build images and push them to DockerHub.

## WHY
As it is discussed in #82 .

## Things to be concerned
In order to make this GitHub Actions works, you have to set `DOCKERHUB_USERNAME` `DOCKERHUB_TOKEN` .

You can validate this workflow with following references.
- https://github.com/docker/metadata-action#tags-input
- https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

### CODE REVIEW

**Comment by kazegusuri** [comment]
thank you for making this PR. I would like to use GitHub docker registry instead of docker hub. Can you fix to use GitHub docker registry?

**Comment by shion1305** [comment]
@kazegusuri  
Thank you for your feedback! Sure, I'll be working on that 👍 

However, I have a question regarding the existing official image on Docker Hub. Do you plan to maintain and update this image alongside the GitHub Docker registry version? IMO, keeping the image on Docker Hub updated and available is beneficial as long as if there are no additional costs involved.

**Comment by toga4** [comment]
@kazegusuri @shion1305 
Hello, any update on this PR?
I would like to use the latest version of wrench as a container image and would be happy to see this PR go forward.
Please let me know if there is anything I can do to help.

**Comment by Shion1305** [comment]
@toga4 Sorry for not making any progress on this..! Image on GHCR is now made available by #111 , so I let this close.

**Comment by toga4** [comment]
good news!

**Pull request closed without merging**
