### PR TITLE
pkg/spanner/client: Add optional option.ClientOption parameters to Ne…

### LINKED ISSUE #59: Support passing option.ClientOption to NewClient in the spanner pkg
## WHAT
Make it so it's possible to instantiate the client in wrench/pkg/spanner with option.ClientOption - perhaps like this:

`func NewClient(ctx context.Context, config *Config, opts ...option.ClientOption) (*Client, error) `

## WHY
I'm trying to use spannertest for unit testing and would like to perform a wrench migration on a new inmem fake db instance. However, I'd also like to avoid using SPANNER_EMULATOR_HOST as I'd like to have multiple instances of spannertest running in the unit test suite.

It is the case that a normal spanner Client can be instantiated such that it uses the spannertest server by passing option.WithGRPCConn(conn) to spanner.NewClient with conn being a gRPC connection to the spannertest server. Perhaps the wrench NewClient could also be able to interact with a spannertest server by instantiating the spanner.Client and the apiv1.DatabaseAdminClient with this option?

### PR DESCRIPTION
**Pull request by mskwon**
…wClient constructor

Fixes #59

## WHAT

This changes the constructor signature for the wrench client so that client options can be passed to the wrapped spanner clients. As the options are passed as a variadic parameter, there is no impact on pre-existing code.

## WHY

The ability to pass client options allows for the passing of [option.WithGRPCConn](https://pkg.go.dev/google.golang.org/api/option#WithGRPCConn). This makes it so that wrench will work with [spannertest](https://pkg.go.dev/cloud.google.com/go/spanner/spannertest) - an in-memory fake Cloud Spanner which can be used for unit tests.

### CODE REVIEW

**Comment by kazegusuri** [comment]
Please sign the CLA.

**Comment by mskwon** [comment]
Apologies for the delay here

**Comment by mskwon** [comment]
Bump

**Comment by kazegusuri** [comment]
Thank you for making this PR. I thought the option should be inside the wrench's config struct instead of first type options because it's the Spanner specific options. I create another PR on the top of your commit.

**Comment by kazegusuri** [comment]
Ah I need to merge this PR first to use your commit because we can't use other merge options except squash and merge.

**Review by kazegusuri — APPROVED** [review]

**Pull request merged**
