### PR TITLE
Replace spansql

### PR DESCRIPTION
**Pull request by apstndb**
## WHAT

Replace spansql with statement separator which is derived from spanner-cli implementation.

## WHY

#83 

## TODO

- [ ] Add tests

### CODE REVIEW

**Comment by kazegusuri** [comment]
hmm, this seems a similar implementation in spansql package. This is another kind of parser I think so it's not good to have the implementation inside each OSS.
It is better to have an independent library that contains this kind of parser. Or I think it's enough if spansql supports this feature. The current problem is that spansql does not support parsing raw statements without parsing the details of the statement.
So if spansql provides parseRawStatements() function that returns  raw statements as array of string I think it's the best.

**Comment by apstndb** [comment]
It is not a Cloud Spanner client library so I don't think it can be merged into https://github.com/googleapis/google-cloud-go.

IMHO, it can be maintained as a standalone repo in cloudspannerecosystem.
Otherwise I don't want wrench to depend on another repo.

Note:
spanner-cli needs to handle ‘\G‘ separators so they can't reuse the statement separator implementation without some kind of a extention point.

**Comment by apstndb** [comment]
It might be possible to describe it as a helper function for using UpdateDDL and Batch DML.

**Comment by kazegusuri** [comment]
> It is not a Cloud Spanner client library so I don't think it can be merged into https://github.com/googleapis/google-cloud-go.
> spansql was born to implement spannertest but they doesn't need this implementation.

It seems most of the recent changes to spansql are not related to spannertest.

**Comment by apstndb** [comment]
> It seems most of the recent changes to spansql are not related to spannertest.

I think there is a difference between that and this case
because `ParseDDL`, `ParseDML`, and `ParseQuery` is already exported functions and they usually accept PRs to fix them.

**Comment by apstndb** [comment]
I would like to correct one factual error.
ParseDML was added for wrench itself.

](https://github.com/googleapis/google-cloud-go/pull/6349)

**Comment by apstndb** [comment]
>spanner-cli needs to handle `\G` separators so they can't reuse the statement separator implementation without some kind of a extention point.

I have implemented customizable separator for demonstrating purpose.
https://github.com/apstndb/wrench/commit/2bd13506ff45f9a688dae4696ea70fc9c76d8acf

**Comment by apstndb** [comment]
After internal discussion, this PR was closed as it has no chance of being approved unless there is a place to maintain the statement separator.

**Pull request closed without merging**
